# Generated by Django 6.0.2 on 2026-04-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_hub', '0006_documentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdocument',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectdocument',
            name='review_streak',
            field=models.IntegerField(default=0),
        ),
    ]
